################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: Banking Risk
  productionDescription: Create a Banking Hub workspace today for free with instant access to APIs for Fiserv account processing platforms and related banking tech. In minutes, you can begin exploring and experimenting with our APIs – accelerating the path to bringing your pre-integrated financial innovations to market.
  whoIsItFor: Developers seeking to create apps and integrate them to Fiserv banking solutions. 
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: REPLACEME™
featuredFeatures:
  - title: Authorization Service 
    description:  The authorization service is the backbone of the entitlements part of the risk domain. It acts as the principal decision-maker for whether requests are granted or rejected. It's bound to Istio/Envoy via an Open Police Agent sidecar which will relay the authorization request on the authorization service.
    tags: []
    bullets: []  
    #links: ["docs/fintechs/risk.md"]
    relatedDocs:
      - relatedAPI: 
        title: Add System Entitlement 
        description: Creates a system level entitlement 
        type: "post"        
        path: "/provider/risk/v1/entitlements/system"
      - relatedAPI: 
        title: Get System Entitlement 
        description: Retrieves system level entitlement
        type: "get"        
        path: "/provider/risk/v1/entitlements/system"
      - relatedAPI: 
        title: Get by ID System Entitlement 
        description: Retrieves specific system level entitlement
        type: "get"        
        path: "/provider/risk/v1/entitlements/system/{id}"
    relatedAPIs:
      - relatedAPI: 
        title: REPLACEME
        description: REPLACEME
        type: "patch"        
        path: "/v1/REPLACEME1"
      - relatedAPI: 
        title: REPLACEME
        description: REPLACEME
        type: "post"        
        path: "/v1/REPLACEME2"
      - relatedAPI: 
        title: REPLACEME
        description: REPLACEME
        type: "get"        
        path: "/v1/REPLACEME3"
